// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResidentialManagement.Api.Data;

#nullable disable

namespace ResidentialManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806140535_AddNotificationUniqueIndex")]
    partial class AddNotificationUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FloorCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "Code")
                        .IsUnique();

                    b.ToTable("Buildings", t =>
                        {
                            t.HasCheckConstraint("CK_Buildings_FloorCount_Range", "[FloorCount] >= 1 AND [FloorCount] <= 200");
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.DueDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DueDay")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("DueDefinitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_DueDefinitions_Amount_Positive", "[Amount] > 0");

                            t.HasCheckConstraint("CK_DueDefinitions_DueDay_Range", "[DueDay] >= 1 AND [DueDay] <= 28");
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.DuePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DueDefinitionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IssuedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IssuedByUserId");

                    b.HasIndex("DueDefinitionId", "Year", "Month")
                        .IsUnique()
                        .HasFilter("[Status] <> 'CANCELLED'");

                    b.ToTable("DuePeriods", null, t =>
                        {
                            t.HasCheckConstraint("CK_DuePeriods_Month_Range", "[Month] >= 1 AND [Month] <= 12");

                            t.HasCheckConstraint("CK_DuePeriods_Status_Allowed", "[Status] IN ('DRAFT', 'ISSUED', 'CANCELLED')");

                            t.HasCheckConstraint("CK_DuePeriods_UnitAmount_Positive", "[UnitAmount] > 0");

                            t.HasCheckConstraint("CK_DuePeriods_Year_Range", "[Year] >= 2020 AND [Year] <= 2100");
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("VendorName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExpenseDate");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Expenses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Expenses_Amount_Positive", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.ManagerAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("EndReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EndedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ManagerUserId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("EndedByUserId");

                    b.HasIndex("BuildingId", "IsActive");

                    b.HasIndex("ManagerUserId", "BuildingId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1 AND [BuildingId] IS NOT NULL");

                    b.HasIndex("ManagerUserId", "IsActive");

                    b.HasIndex("ManagerUserId", "PropertyId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1 AND [BuildingId] IS NULL");

                    b.HasIndex("PropertyId", "IsActive");

                    b.ToTable("ManagerAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_ManagerAssignments_Active_End_State", "([IsActive] = 1 AND [EndedAt] IS NULL AND [EndedByUserId] IS NULL) OR ([IsActive] = 0 AND [EndedAt] IS NOT NULL)");

                            t.HasCheckConstraint("CK_ManagerAssignments_EndedAt_After_AssignedAt", "[EndedAt] IS NULL OR [EndedAt] >= [AssignedAt]");
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedEntityName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsDismissed");

                    b.HasIndex("UserId", "IsRead");

                    b.HasIndex("UserId", "IsDismissed", "IsRead");

                    b.HasIndex("UserId", "NotificationType", "RelatedEntityName", "RelatedEntityId")
                        .IsUnique()
                        .HasFilter("[RelatedEntityName] IS NOT NULL AND [RelatedEntityId] IS NOT NULL");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.OccupancyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("OccupancyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "OWNER",
                            Description = "Property owner associated with the unit",
                            IsActive = true,
                            Name = "Owner"
                        },
                        new
                        {
                            Id = 2,
                            Code = "TENANT",
                            Description = "Tenant currently or historically associated with the unit",
                            IsActive = true,
                            Name = "Tenant"
                        },
                        new
                        {
                            Id = 3,
                            Code = "HOUSEHOLD_MEMBER",
                            Description = "Household member residing in the unit without ownership or tenancy responsibility",
                            IsActive = true,
                            Name = "Household Member"
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PayerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PaymentSubmissionId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnitChargeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PayerUserId");

                    b.HasIndex("PaymentSubmissionId")
                        .IsUnique()
                        .HasFilter("[PaymentSubmissionId] IS NOT NULL");

                    b.HasIndex("UnitChargeId", "IsCancelled");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount_Positive", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.PaymentSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiptAttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("UnitChargeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("UnitChargeId");

                    b.ToTable("PaymentSubmissions", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaymentSubmissions_Amount_Positive", "[Amount] > 0");

                            t.HasCheckConstraint("CK_PaymentSubmissions_Status_Allowed", "[Status] IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PropertyTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.PropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PropertyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "RESIDENTIAL_COMPLEX",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Çok bloklu veya sosyal tesisli konut sitesi",
                            IsActive = true,
                            Name = "Site / Konut Sitesi"
                        },
                        new
                        {
                            Id = 2,
                            Code = "SINGLE_APARTMENT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tek bloklu konut binası",
                            IsActive = true,
                            Name = "Apartman"
                        },
                        new
                        {
                            Id = 3,
                            Code = "COMMERCIAL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "İş merkezi, çarşı veya ticari kompleks",
                            IsActive = true,
                            Name = "Ticari Kompleks"
                        },
                        new
                        {
                            Id = 4,
                            Code = "MIXED_USE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hem konut hem ticari birimleri olan kompleks",
                            IsActive = true,
                            Name = "Karma Kullanım"
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADMIN",
                            Description = "Full system administration access",
                            IsActive = true,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MANAGER",
                            Description = "Manages assigned properties and operational records",
                            IsActive = true,
                            Name = "Property Manager"
                        },
                        new
                        {
                            Id = 3,
                            Code = "RESIDENT",
                            Description = "Resident access to assigned property and unit information",
                            IsActive = true,
                            Name = "Resident"
                        },
                        new
                        {
                            Id = 4,
                            Code = "TECHNICAL_STAFF",
                            Description = "Handles maintenance and technical operations",
                            IsActive = true,
                            Name = "Technical Staff"
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("GrossArea")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NetArea")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UnitTypeId");

                    b.HasIndex("BuildingId", "UnitNumber")
                        .IsUnique();

                    b.ToTable("Units", t =>
                        {
                            t.HasCheckConstraint("CK_Units_GrossArea_Positive", "[GrossArea] IS NULL OR [GrossArea] > 0");

                            t.HasCheckConstraint("CK_Units_NetArea_NotGreaterThanGrossArea", "[GrossArea] IS NULL OR [NetArea] IS NULL OR [NetArea] <= [GrossArea]");

                            t.HasCheckConstraint("CK_Units_NetArea_Positive", "[NetArea] IS NULL OR [NetArea] > 0");
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.UnitCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ChargeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DuePeriodId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpenseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DuePeriodId");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("DueDate", "IsCancelled");

                    b.HasIndex("UnitId", "DueDate");

                    b.ToTable("UnitCharges", null, t =>
                        {
                            t.HasCheckConstraint("CK_UnitCharges_Amount_Positive", "[Amount] > 0");

                            t.HasCheckConstraint("CK_UnitCharges_Source_Consistency", "([ChargeType] = 'DUES' AND [DuePeriodId] IS NOT NULL AND [ExpenseId] IS NULL) OR ([ChargeType] = 'EXPENSE_RECOVERY' AND [ExpenseId] IS NOT NULL AND [DuePeriodId] IS NULL) OR ([ChargeType] = 'MANUAL' AND [DuePeriodId] IS NULL AND [ExpenseId] IS NULL)");
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.UnitOccupancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OccupancyTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OccupancyTypeId");

                    b.HasIndex("UnitId");

                    b.HasIndex("UserId");

                    b.HasIndex("UnitId", "IsActive");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("UnitOccupancies", t =>
                        {
                            t.HasCheckConstraint("CK_UnitOccupancies_EndDate_After_StartDate", "[EndDate] IS NULL OR [EndDate] >= [StartDate]");
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.UnitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UnitTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "APARTMENT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Konut / Mesken birimi",
                            IsActive = true,
                            Name = "Daire"
                        },
                        new
                        {
                            Id = 2,
                            Code = "SHOP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ticari dükkan veya mağaza",
                            IsActive = true,
                            Name = "Dükkan"
                        },
                        new
                        {
                            Id = 3,
                            Code = "OFFICE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Büro veya çalışma alanı",
                            IsActive = true,
                            Name = "Ofis"
                        },
                        new
                        {
                            Id = 4,
                            Code = "STORAGE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bağımsız depo veya sığınak alanı",
                            IsActive = true,
                            Name = "Depo"
                        },
                        new
                        {
                            Id = 5,
                            Code = "PARKING_SPACE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tahsisli araç park yeri",
                            IsActive = true,
                            Name = "Otopark Alanı"
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Building", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.Property", "Property")
                        .WithMany("Buildings")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.DueDefinition", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResidentialManagement.Api.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Building");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Property");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.DuePeriod", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.User", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResidentialManagement.Api.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.DueDefinition", "DueDefinition")
                        .WithMany("DuePeriods")
                        .HasForeignKey("DueDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.User", "IssuedByUser")
                        .WithMany()
                        .HasForeignKey("IssuedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CancelledByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DueDefinition");

                    b.Navigation("IssuedByUser");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Expense", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResidentialManagement.Api.Entities.User", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResidentialManagement.Api.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Building");

                    b.Navigation("CancelledByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Property");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.ManagerAssignment", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResidentialManagement.Api.Entities.User", "EndedByUser")
                        .WithMany()
                        .HasForeignKey("EndedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResidentialManagement.Api.Entities.User", "ManagerUser")
                        .WithMany()
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Building");

                    b.Navigation("EndedByUser");

                    b.Navigation("ManagerUser");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Notification", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Payment", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.User", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResidentialManagement.Api.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.User", "PayerUser")
                        .WithMany()
                        .HasForeignKey("PayerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResidentialManagement.Api.Entities.PaymentSubmission", "PaymentSubmission")
                        .WithMany()
                        .HasForeignKey("PaymentSubmissionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResidentialManagement.Api.Entities.UnitCharge", "UnitCharge")
                        .WithMany("Payments")
                        .HasForeignKey("UnitChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CancelledByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("PayerUser");

                    b.Navigation("PaymentSubmission");

                    b.Navigation("UnitCharge");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.PaymentSubmission", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.User", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResidentialManagement.Api.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResidentialManagement.Api.Entities.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.UnitCharge", "UnitCharge")
                        .WithMany("PaymentSubmissions")
                        .HasForeignKey("UnitChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CancelledByUser");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("SubmittedByUser");

                    b.Navigation("UnitCharge");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Property", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.PropertyType", "PropertyTypeLookup")
                        .WithMany()
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PropertyTypeLookup");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Unit", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.Building", "Building")
                        .WithMany("Units")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.UnitType", "UnitType")
                        .WithMany("Units")
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.UnitCharge", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.User", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResidentialManagement.Api.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.DuePeriod", "DuePeriod")
                        .WithMany("UnitCharges")
                        .HasForeignKey("DuePeriodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResidentialManagement.Api.Entities.Expense", "Expense")
                        .WithMany("UnitCharges")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResidentialManagement.Api.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CancelledByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DuePeriod");

                    b.Navigation("Expense");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.UnitOccupancy", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.OccupancyType", "OccupancyType")
                        .WithMany("UnitOccupancies")
                        .HasForeignKey("OccupancyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.Unit", "Unit")
                        .WithMany("UnitOccupancies")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.User", "User")
                        .WithMany("UnitOccupancies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OccupancyType");

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.UserRole", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Building", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.DueDefinition", b =>
                {
                    b.Navigation("DuePeriods");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.DuePeriod", b =>
                {
                    b.Navigation("UnitCharges");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Expense", b =>
                {
                    b.Navigation("UnitCharges");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.OccupancyType", b =>
                {
                    b.Navigation("UnitOccupancies");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Property", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Unit", b =>
                {
                    b.Navigation("UnitOccupancies");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.UnitCharge", b =>
                {
                    b.Navigation("PaymentSubmissions");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.UnitType", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.User", b =>
                {
                    b.Navigation("UnitOccupancies");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
