// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResidentialManagement.Api.Data;

#nullable disable

namespace ResidentialManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730205710_AddUnits")]
    partial class AddUnits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FloorCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "Code")
                        .IsUnique();

                    b.ToTable("Buildings", t =>
                        {
                            t.HasCheckConstraint("CK_Buildings_FloorCount_Range", "[FloorCount] >= 1 AND [FloorCount] <= 200");
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PropertyTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.PropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PropertyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "RESIDENTIAL_COMPLEX",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Çok bloklu veya sosyal tesisli konut sitesi",
                            IsActive = true,
                            Name = "Site / Konut Sitesi"
                        },
                        new
                        {
                            Id = 2,
                            Code = "SINGLE_APARTMENT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tek bloklu konut binası",
                            IsActive = true,
                            Name = "Apartman"
                        },
                        new
                        {
                            Id = 3,
                            Code = "COMMERCIAL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "İş merkezi, çarşı veya ticari kompleks",
                            IsActive = true,
                            Name = "Ticari Kompleks"
                        },
                        new
                        {
                            Id = 4,
                            Code = "MIXED_USE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hem konut hem ticari birimleri olan kompleks",
                            IsActive = true,
                            Name = "Karma Kullanım"
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("GrossArea")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NetArea")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UnitTypeId");

                    b.HasIndex("BuildingId", "UnitNumber")
                        .IsUnique();

                    b.ToTable("Units", t =>
                        {
                            t.HasCheckConstraint("CK_Units_GrossArea_Positive", "[GrossArea] IS NULL OR [GrossArea] > 0");

                            t.HasCheckConstraint("CK_Units_NetArea_NotGreaterThanGrossArea", "[GrossArea] IS NULL OR [NetArea] IS NULL OR [NetArea] <= [GrossArea]");

                            t.HasCheckConstraint("CK_Units_NetArea_Positive", "[NetArea] IS NULL OR [NetArea] > 0");
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.UnitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UnitTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "APARTMENT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Konut / Mesken birimi",
                            IsActive = true,
                            Name = "Daire"
                        },
                        new
                        {
                            Id = 2,
                            Code = "SHOP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ticari dükkan veya mağaza",
                            IsActive = true,
                            Name = "Dükkan"
                        },
                        new
                        {
                            Id = 3,
                            Code = "OFFICE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Büro veya çalışma alanı",
                            IsActive = true,
                            Name = "Ofis"
                        },
                        new
                        {
                            Id = 4,
                            Code = "STORAGE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bağımsız depo veya sığınak alanı",
                            IsActive = true,
                            Name = "Depo"
                        },
                        new
                        {
                            Id = 5,
                            Code = "PARKING_SPACE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tahsisli araç park yeri",
                            IsActive = true,
                            Name = "Otopark Alanı"
                        });
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Building", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.Property", "Property")
                        .WithMany("Buildings")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Property", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.PropertyType", "PropertyTypeLookup")
                        .WithMany()
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PropertyTypeLookup");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Unit", b =>
                {
                    b.HasOne("ResidentialManagement.Api.Entities.Building", "Building")
                        .WithMany("Units")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialManagement.Api.Entities.UnitType", "UnitType")
                        .WithMany("Units")
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Building", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.Property", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("ResidentialManagement.Api.Entities.UnitType", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
